### ISSUE TITLE
How to use your package?

### ISSUE THREAD

**Issue by dfrankow** [GeeWee/django-auto-prefetching#2]
I am having [performance issues with drf](https://stackoverflow.com/questions/56266367/how-to-speed-up-djangorestframework-bulk-inserts). I feel like your library might help, but I can't figure out how to use it, or if it pertains. All the things I try result in no impact. Please see the stackoverflow question.

I'd appreciate any thoughts.

**Comment by GeeWee** [comment]
Yeah the documentations been in a bit of a sorry state, I've updated it to make it more clear. 
Unfortunately I don't think it's going to help much with inserts, but feel free to give it a shot and let me know if it helps you!

**Comment by dfrankow** [comment]
Gotcha.

The stackoverflow question mentions four queries. The last one (4) is an insert. The third one I was able to turn off. But numbers 1 and 2 are foreign-key queries, one of which is the same query repeated over and over because fk1 doesn't change. This feels like it would be helped by a pre-fetch. But, again, I can't get it to work.

**Comment by GeeWee** [comment]
Unfortunately Django checks foreign keys on insert, even though things are prefetched. I think you might be able to get around it by using `bulk_insert`, but unsure.
