### ISSUE TITLE
function based view support

### ISSUE THREAD

**Issue by sodrooome** [GeeWee/django-auto-prefetching#29]
Hi, i want to ask you something. Related the issue on #18, does this works in function based view? like, using `method_decorator`  or something like that?

**Comment by GeeWee** [comment]
It depends on how the function view is implemented. All `django-auto-prefetching` really cares about is getting a queryset and a serializer.
The relevant function you call is `django_auto_prefetching.prefetch(queryset,self.serializer_class`

So in essence: If you use a serializer to render the model, you can use the library, if not - you're out of luck unfortunately.
