### ISSUE TITLE
Opinion on djangorestframework-serializer-extensions

### ISSUE THREAD

**Issue by jpmckinney** [GeeWee/django-auto-prefetching#32]
I see djangorestframework-serializer-extensions provides similar functionality with its `extensions_auto_optimize = True` ([documented here](https://django-rest-framework-serializer-extensions.readthedocs.io/en/latest/auto-optimizations/)). Are there any relevant differences to your knowledge?

https://github.com/evenicoulddoit/django-rest-framework-serializer-extensions

**Comment by GeeWee** [comment]
I hadn't seen that before.
It seems approximately like the same way of implementing it when skimming the code. I would wager they probably do approximately the same thing.

**Comment by jpmckinney** [comment]
Thanks for checking, I appreciate it!

**Comment by GeeWee** [comment]
You're welcome!
