### ISSUE TITLE
dotted notation to traversel in serializer  gives AttributeError

### ISSUE THREAD

**Issue by Javedgouri** [GeeWee/django-auto-prefetching#37]
dotted notation to traverse attributes are not working 

user_platforms = UserPlatformSerializer(source='user.user_platforms', read_only=True, many=True)

AttributeError: Cannot find 'user.user_platforms' on Artist object, 'user.user_platforms__platform__logo' is an invalid parameter to prefetch_related()

**Comment by GeeWee** [comment]
I'd love for this to get fixed - unfortunately I don't have a lot of time to dedicate to this project currently. Pull requests are very welcome.

**Comment by sgarcialaguna-mms** [comment]
I recently stumbled over this. Couldn't one simply do

```python
    select_related = [s.replace('.', '__') for s in select_related]
    prefetch_related = [s.replace('.', '__') for s in prefetch_related]
```

I tried this out locally and it seemed to work, but I'm not sure it won't break in other places.

**Comment by GeeWee** [comment]
Yeah that could probably work - we have a reasonably extensive test suite so if you want to submit a PR we should be able to see if it actually breaks anything :)

**Comment by sgarcialaguna-mms** [comment]
Sure, why not:

https://github.com/GeeWee/django-auto-prefetching/pull/44

**Comment by GeeWee** [comment]
Awesome.

**Comment by GeeWee** [comment]
`0.2.11` on PyPi should have this change.
