### ISSUE TITLE
Shouldn't we check the field only if it's inherited from ModelSerializer instead of BaseSerializer?

### ISSUE THREAD

**Issue by JasperSui** [GeeWee/django-auto-prefetching#52]
Hi, thank you for releasing this amazing work, I found it's really a package with great potential.

I tried to adapt my current project to this package, and I found that we are currently checking the `field_instance` as below:

```python
# __init__.py, Line 144

        # We potentially need to recurse deeper
        if isinstance(
                field_instance, (BaseSerializer, RelatedField, ManyRelatedField)
        ) and ...
```

IMHO, should the `BaseSerializer` be replaced with `ModelSerializer`? Because the `serializers.Serializer` is also inherited from `BaseSerializer` which is not the target we want to check if any `select_related` and `prefetch_related` fields should be included.

I know we can exclude the fields by specifying them with `auto_prefetch_excluded_fields` but I'm just curious about the use cases, for me, the `serializers.Serializer` is often used as the request body validator and it's also can be used to generate the API schema with `drf-spectacular` (it's also an awesome package that generates the OpenAPI schema automatically btw).

**Comment by GeeWee** [comment]
I'll be honest I wrote this many years ago and I can't justify why we're checking BaseSerializer and not ModelSerializer. Do you encounter production problems with this or does the further checks for attributes "correctly" filter out stuff? If you encounter issues I'd be open to a PR changing it.

**Comment by JasperSui** [comment]
Thanks for your fast reply! Here is an example for you.

```python
from rest_framework import serializers
from django.db import models, transaction

# Models
class Product(models.Model):
    name = models.CharField()


class Description(models.Model):
    project = models.OneToOneField(Product, on_delete=models.CASCADE)
    body = models.TextField()
    image = models.ImageField()


# Serializers
class DescriptionSerializer(serializers.Serializer):
    body = serializers.CharField()
    image = serializers.ImageField()


class ProductSerializer(serializers.ModelSerializer):
    description = DescriptionSerializer(required=True, write_only=True)

    class Meta:
        model = Product
        fields = "__all__"

    def create(self, validated_data) -> Product:
        description_data = validated_data.pop("description")

        with transaction.atomic():
            product = super().create(validated_data)
            product.description = Description(**description_data)
            product.save()

        return product
```

All I want to do is make sure the `ProductSerializer` can have the correct schema with a write-only description field. And it's obvious that we don't need to count `description` as any `select_related` or `prefetch_related` fields here right? Because it's write-only.

But as I mentioned above, the `serializers.Serializer` is inherited from `serializers.BaseSerializer`, so it will enter the if-else block and be added to the `select_related` or `prefetch_related` fields.

I think we should check if the field instance is `ModelSerializer` but not `BaseSerializer` instead, but what if a `Serializer` has a field that is a `ModelSerializer`? Or should we check if the field is a `BaseSerializer` with `write_only=False` instead?

Please correct me if I'm wrong, thanks!

**Comment by GeeWee** [comment]
Ah, yes perhaps the case of
> I think we should check if the field instance is ModelSerializer but not BaseSerializer instead, but what if a Serializer has a field that is a ModelSerializer?
is the reason for checking for `BaseSerializer`

A check to see if it's a BaseSerializer and has `write_only=True` and then skipping it seems like a sensible solution?

**Comment by JasperSui** [comment]
Yeah, it looks promising to me.

**Comment by GeeWee** [comment]
Feel free to submit a PR!

**Comment by JasperSui** [comment]
Will do in an hour, thanks again!
